/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ImagePath;
import java.io.IOException;

/**
 * InlineResponse20017Crew
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20017Crew {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("credit_id")
  private String creditId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("department")
  private String department = null;

  @SerializedName("job")
  private String job = null;

  @SerializedName("profile_path")
  private ImagePath profilePath = null;

  public InlineResponse20017Crew id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20017Crew creditId(String creditId) {
    this.creditId = creditId;
    return this;
  }

   /**
   * Get creditId
   * @return creditId
  **/
  @ApiModelProperty(value = "")
  public String getCreditId() {
    return creditId;
  }

  public void setCreditId(String creditId) {
    this.creditId = creditId;
  }

  public InlineResponse20017Crew name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20017Crew department(String department) {
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @ApiModelProperty(value = "")
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public InlineResponse20017Crew job(String job) {
    this.job = job;
    return this;
  }

   /**
   * Get job
   * @return job
  **/
  @ApiModelProperty(value = "")
  public String getJob() {
    return job;
  }

  public void setJob(String job) {
    this.job = job;
  }

  public InlineResponse20017Crew profilePath(ImagePath profilePath) {
    this.profilePath = profilePath;
    return this;
  }

   /**
   * Get profilePath
   * @return profilePath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getProfilePath() {
    return profilePath;
  }

  public void setProfilePath(ImagePath profilePath) {
    this.profilePath = profilePath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20017Crew inlineResponse20017Crew = (InlineResponse20017Crew) o;
    return Objects.equals(this.id, inlineResponse20017Crew.id) &&
        Objects.equals(this.creditId, inlineResponse20017Crew.creditId) &&
        Objects.equals(this.name, inlineResponse20017Crew.name) &&
        Objects.equals(this.department, inlineResponse20017Crew.department) &&
        Objects.equals(this.job, inlineResponse20017Crew.job) &&
        Objects.equals(this.profilePath, inlineResponse20017Crew.profilePath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creditId, name, department, job, profilePath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20017Crew {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creditId: ").append(toIndentedString(creditId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    job: ").append(toIndentedString(job)).append("\n");
    sb.append("    profilePath: ").append(toIndentedString(profilePath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

