/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ImagePath;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20014Cast
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20014Cast {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("original_language")
  private String originalLanguage = null;

  @SerializedName("episode_count")
  private Integer episodeCount = null;

  @SerializedName("overview")
  private String overview = null;

  @SerializedName("origin_country")
  private List<String> originCountry = null;

  @SerializedName("original_name")
  private String originalName = null;

  @SerializedName("genre_ids")
  private List<Integer> genreIds = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("media_type")
  private String mediaType = null;

  @SerializedName("poster_path")
  private ImagePath posterPath = null;

  @SerializedName("first_air_date")
  private String firstAirDate = null;

  @SerializedName("vote_count")
  private Integer voteCount = null;

  @SerializedName("character")
  private String character = null;

  @SerializedName("backdrop_path")
  private ImagePath backdropPath = null;

  @SerializedName("popularity")
  private BigDecimal popularity = null;

  @SerializedName("credit_id")
  private String creditId = null;

  @SerializedName("original_title")
  private String originalTitle = null;

  @SerializedName("video")
  private Boolean video = null;

  @SerializedName("release_date")
  private String releaseDate = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("adult")
  private Boolean adult = null;

  public InlineResponse20014Cast id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20014Cast originalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
    return this;
  }

   /**
   * Get originalLanguage
   * @return originalLanguage
  **/
  @ApiModelProperty(value = "")
  public String getOriginalLanguage() {
    return originalLanguage;
  }

  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }

  public InlineResponse20014Cast episodeCount(Integer episodeCount) {
    this.episodeCount = episodeCount;
    return this;
  }

   /**
   * Get episodeCount
   * @return episodeCount
  **/
  @ApiModelProperty(value = "")
  public Integer getEpisodeCount() {
    return episodeCount;
  }

  public void setEpisodeCount(Integer episodeCount) {
    this.episodeCount = episodeCount;
  }

  public InlineResponse20014Cast overview(String overview) {
    this.overview = overview;
    return this;
  }

   /**
   * Get overview
   * @return overview
  **/
  @ApiModelProperty(value = "")
  public String getOverview() {
    return overview;
  }

  public void setOverview(String overview) {
    this.overview = overview;
  }

  public InlineResponse20014Cast originCountry(List<String> originCountry) {
    this.originCountry = originCountry;
    return this;
  }

  public InlineResponse20014Cast addOriginCountryItem(String originCountryItem) {
    if (this.originCountry == null) {
      this.originCountry = new ArrayList<String>();
    }
    this.originCountry.add(originCountryItem);
    return this;
  }

   /**
   * Get originCountry
   * @return originCountry
  **/
  @ApiModelProperty(value = "")
  public List<String> getOriginCountry() {
    return originCountry;
  }

  public void setOriginCountry(List<String> originCountry) {
    this.originCountry = originCountry;
  }

  public InlineResponse20014Cast originalName(String originalName) {
    this.originalName = originalName;
    return this;
  }

   /**
   * Get originalName
   * @return originalName
  **/
  @ApiModelProperty(value = "")
  public String getOriginalName() {
    return originalName;
  }

  public void setOriginalName(String originalName) {
    this.originalName = originalName;
  }

  public InlineResponse20014Cast genreIds(List<Integer> genreIds) {
    this.genreIds = genreIds;
    return this;
  }

  public InlineResponse20014Cast addGenreIdsItem(Integer genreIdsItem) {
    if (this.genreIds == null) {
      this.genreIds = new ArrayList<Integer>();
    }
    this.genreIds.add(genreIdsItem);
    return this;
  }

   /**
   * Get genreIds
   * @return genreIds
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getGenreIds() {
    return genreIds;
  }

  public void setGenreIds(List<Integer> genreIds) {
    this.genreIds = genreIds;
  }

  public InlineResponse20014Cast name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20014Cast mediaType(String mediaType) {
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Get mediaType
   * @return mediaType
  **/
  @ApiModelProperty(value = "")
  public String getMediaType() {
    return mediaType;
  }

  public void setMediaType(String mediaType) {
    this.mediaType = mediaType;
  }

  public InlineResponse20014Cast posterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
    return this;
  }

   /**
   * Get posterPath
   * @return posterPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getPosterPath() {
    return posterPath;
  }

  public void setPosterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
  }

  public InlineResponse20014Cast firstAirDate(String firstAirDate) {
    this.firstAirDate = firstAirDate;
    return this;
  }

   /**
   * Get firstAirDate
   * @return firstAirDate
  **/
  @ApiModelProperty(value = "")
  public String getFirstAirDate() {
    return firstAirDate;
  }

  public void setFirstAirDate(String firstAirDate) {
    this.firstAirDate = firstAirDate;
  }

  public InlineResponse20014Cast voteCount(Integer voteCount) {
    this.voteCount = voteCount;
    return this;
  }

   /**
   * Get voteCount
   * @return voteCount
  **/
  @ApiModelProperty(value = "")
  public Integer getVoteCount() {
    return voteCount;
  }

  public void setVoteCount(Integer voteCount) {
    this.voteCount = voteCount;
  }

  public InlineResponse20014Cast character(String character) {
    this.character = character;
    return this;
  }

   /**
   * Get character
   * @return character
  **/
  @ApiModelProperty(value = "")
  public String getCharacter() {
    return character;
  }

  public void setCharacter(String character) {
    this.character = character;
  }

  public InlineResponse20014Cast backdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
    return this;
  }

   /**
   * Get backdropPath
   * @return backdropPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getBackdropPath() {
    return backdropPath;
  }

  public void setBackdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
  }

  public InlineResponse20014Cast popularity(BigDecimal popularity) {
    this.popularity = popularity;
    return this;
  }

   /**
   * Get popularity
   * @return popularity
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPopularity() {
    return popularity;
  }

  public void setPopularity(BigDecimal popularity) {
    this.popularity = popularity;
  }

  public InlineResponse20014Cast creditId(String creditId) {
    this.creditId = creditId;
    return this;
  }

   /**
   * Get creditId
   * @return creditId
  **/
  @ApiModelProperty(value = "")
  public String getCreditId() {
    return creditId;
  }

  public void setCreditId(String creditId) {
    this.creditId = creditId;
  }

  public InlineResponse20014Cast originalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
    return this;
  }

   /**
   * Get originalTitle
   * @return originalTitle
  **/
  @ApiModelProperty(value = "")
  public String getOriginalTitle() {
    return originalTitle;
  }

  public void setOriginalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
  }

  public InlineResponse20014Cast video(Boolean video) {
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @ApiModelProperty(value = "")
  public Boolean isVideo() {
    return video;
  }

  public void setVideo(Boolean video) {
    this.video = video;
  }

  public InlineResponse20014Cast releaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @ApiModelProperty(value = "")
  public String getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
  }

  public InlineResponse20014Cast title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public InlineResponse20014Cast adult(Boolean adult) {
    this.adult = adult;
    return this;
  }

   /**
   * Get adult
   * @return adult
  **/
  @ApiModelProperty(value = "")
  public Boolean isAdult() {
    return adult;
  }

  public void setAdult(Boolean adult) {
    this.adult = adult;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20014Cast inlineResponse20014Cast = (InlineResponse20014Cast) o;
    return Objects.equals(this.id, inlineResponse20014Cast.id) &&
        Objects.equals(this.originalLanguage, inlineResponse20014Cast.originalLanguage) &&
        Objects.equals(this.episodeCount, inlineResponse20014Cast.episodeCount) &&
        Objects.equals(this.overview, inlineResponse20014Cast.overview) &&
        Objects.equals(this.originCountry, inlineResponse20014Cast.originCountry) &&
        Objects.equals(this.originalName, inlineResponse20014Cast.originalName) &&
        Objects.equals(this.genreIds, inlineResponse20014Cast.genreIds) &&
        Objects.equals(this.name, inlineResponse20014Cast.name) &&
        Objects.equals(this.mediaType, inlineResponse20014Cast.mediaType) &&
        Objects.equals(this.posterPath, inlineResponse20014Cast.posterPath) &&
        Objects.equals(this.firstAirDate, inlineResponse20014Cast.firstAirDate) &&
        Objects.equals(this.voteCount, inlineResponse20014Cast.voteCount) &&
        Objects.equals(this.character, inlineResponse20014Cast.character) &&
        Objects.equals(this.backdropPath, inlineResponse20014Cast.backdropPath) &&
        Objects.equals(this.popularity, inlineResponse20014Cast.popularity) &&
        Objects.equals(this.creditId, inlineResponse20014Cast.creditId) &&
        Objects.equals(this.originalTitle, inlineResponse20014Cast.originalTitle) &&
        Objects.equals(this.video, inlineResponse20014Cast.video) &&
        Objects.equals(this.releaseDate, inlineResponse20014Cast.releaseDate) &&
        Objects.equals(this.title, inlineResponse20014Cast.title) &&
        Objects.equals(this.adult, inlineResponse20014Cast.adult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, originalLanguage, episodeCount, overview, originCountry, originalName, genreIds, name, mediaType, posterPath, firstAirDate, voteCount, character, backdropPath, popularity, creditId, originalTitle, video, releaseDate, title, adult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20014Cast {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    originalLanguage: ").append(toIndentedString(originalLanguage)).append("\n");
    sb.append("    episodeCount: ").append(toIndentedString(episodeCount)).append("\n");
    sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
    sb.append("    originCountry: ").append(toIndentedString(originCountry)).append("\n");
    sb.append("    originalName: ").append(toIndentedString(originalName)).append("\n");
    sb.append("    genreIds: ").append(toIndentedString(genreIds)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
    sb.append("    firstAirDate: ").append(toIndentedString(firstAirDate)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("    character: ").append(toIndentedString(character)).append("\n");
    sb.append("    backdropPath: ").append(toIndentedString(backdropPath)).append("\n");
    sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
    sb.append("    creditId: ").append(toIndentedString(creditId)).append("\n");
    sb.append("    originalTitle: ").append(toIndentedString(originalTitle)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    adult: ").append(toIndentedString(adult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

