/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ImagePath;
import io.swagger.client.model.InlineResponse20043ProductionCountries;
import io.swagger.client.model.InlineResponse20061CreatedBy;
import io.swagger.client.model.InlineResponse20061LastEpisodeToAir;
import io.swagger.client.model.InlineResponse20061Networks;
import io.swagger.client.model.InlineResponse20061ProductionCompanies;
import io.swagger.client.model.InlineResponse20061Seasons;
import io.swagger.client.model.InlineResponse20061SpokenLanguages;
import io.swagger.client.model.InlineResponse2009Results;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20061
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20061 {
  @SerializedName("backdrop_path")
  private ImagePath backdropPath = null;

  @SerializedName("created_by")
  private List<InlineResponse20061CreatedBy> createdBy = null;

  @SerializedName("episode_run_time")
  private List<Integer> episodeRunTime = null;

  @SerializedName("first_air_date")
  private String firstAirDate = null;

  @SerializedName("genres")
  private List<InlineResponse2009Results> genres = null;

  @SerializedName("homepage")
  private String homepage = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("in_production")
  private Boolean inProduction = null;

  @SerializedName("languages")
  private List<String> languages = null;

  @SerializedName("last_air_date")
  private String lastAirDate = null;

  @SerializedName("last_episode_to_air")
  private InlineResponse20061LastEpisodeToAir lastEpisodeToAir = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("networks")
  private List<InlineResponse20061Networks> networks = null;

  @SerializedName("number_of_episodes")
  private Integer numberOfEpisodes = null;

  @SerializedName("number_of_seasons")
  private Integer numberOfSeasons = null;

  @SerializedName("origin_country")
  private List<String> originCountry = null;

  @SerializedName("original_language")
  private String originalLanguage = null;

  @SerializedName("original_name")
  private String originalName = null;

  @SerializedName("overview")
  private String overview = null;

  @SerializedName("popularity")
  private BigDecimal popularity = null;

  @SerializedName("poster_path")
  private ImagePath posterPath = null;

  @SerializedName("production_companies")
  private List<InlineResponse20061ProductionCompanies> productionCompanies = null;

  @SerializedName("production_countries")
  private List<InlineResponse20043ProductionCountries> productionCountries = null;

  @SerializedName("seasons")
  private List<InlineResponse20061Seasons> seasons = null;

  @SerializedName("spoken_languages")
  private List<InlineResponse20061SpokenLanguages> spokenLanguages = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("tagline")
  private String tagline = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("vote_average")
  private BigDecimal voteAverage = null;

  @SerializedName("vote_count")
  private Integer voteCount = null;

  public InlineResponse20061 backdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
    return this;
  }

   /**
   * Get backdropPath
   * @return backdropPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getBackdropPath() {
    return backdropPath;
  }

  public void setBackdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
  }

  public InlineResponse20061 createdBy(List<InlineResponse20061CreatedBy> createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  public InlineResponse20061 addCreatedByItem(InlineResponse20061CreatedBy createdByItem) {
    if (this.createdBy == null) {
      this.createdBy = new ArrayList<InlineResponse20061CreatedBy>();
    }
    this.createdBy.add(createdByItem);
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20061CreatedBy> getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(List<InlineResponse20061CreatedBy> createdBy) {
    this.createdBy = createdBy;
  }

  public InlineResponse20061 episodeRunTime(List<Integer> episodeRunTime) {
    this.episodeRunTime = episodeRunTime;
    return this;
  }

  public InlineResponse20061 addEpisodeRunTimeItem(Integer episodeRunTimeItem) {
    if (this.episodeRunTime == null) {
      this.episodeRunTime = new ArrayList<Integer>();
    }
    this.episodeRunTime.add(episodeRunTimeItem);
    return this;
  }

   /**
   * Get episodeRunTime
   * @return episodeRunTime
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getEpisodeRunTime() {
    return episodeRunTime;
  }

  public void setEpisodeRunTime(List<Integer> episodeRunTime) {
    this.episodeRunTime = episodeRunTime;
  }

  public InlineResponse20061 firstAirDate(String firstAirDate) {
    this.firstAirDate = firstAirDate;
    return this;
  }

   /**
   * Get firstAirDate
   * @return firstAirDate
  **/
  @ApiModelProperty(value = "")
  public String getFirstAirDate() {
    return firstAirDate;
  }

  public void setFirstAirDate(String firstAirDate) {
    this.firstAirDate = firstAirDate;
  }

  public InlineResponse20061 genres(List<InlineResponse2009Results> genres) {
    this.genres = genres;
    return this;
  }

  public InlineResponse20061 addGenresItem(InlineResponse2009Results genresItem) {
    if (this.genres == null) {
      this.genres = new ArrayList<InlineResponse2009Results>();
    }
    this.genres.add(genresItem);
    return this;
  }

   /**
   * Get genres
   * @return genres
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2009Results> getGenres() {
    return genres;
  }

  public void setGenres(List<InlineResponse2009Results> genres) {
    this.genres = genres;
  }

  public InlineResponse20061 homepage(String homepage) {
    this.homepage = homepage;
    return this;
  }

   /**
   * Get homepage
   * @return homepage
  **/
  @ApiModelProperty(value = "")
  public String getHomepage() {
    return homepage;
  }

  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public InlineResponse20061 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20061 inProduction(Boolean inProduction) {
    this.inProduction = inProduction;
    return this;
  }

   /**
   * Get inProduction
   * @return inProduction
  **/
  @ApiModelProperty(value = "")
  public Boolean isInProduction() {
    return inProduction;
  }

  public void setInProduction(Boolean inProduction) {
    this.inProduction = inProduction;
  }

  public InlineResponse20061 languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  public InlineResponse20061 addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<String>();
    }
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * Get languages
   * @return languages
  **/
  @ApiModelProperty(value = "")
  public List<String> getLanguages() {
    return languages;
  }

  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }

  public InlineResponse20061 lastAirDate(String lastAirDate) {
    this.lastAirDate = lastAirDate;
    return this;
  }

   /**
   * Get lastAirDate
   * @return lastAirDate
  **/
  @ApiModelProperty(value = "")
  public String getLastAirDate() {
    return lastAirDate;
  }

  public void setLastAirDate(String lastAirDate) {
    this.lastAirDate = lastAirDate;
  }

  public InlineResponse20061 lastEpisodeToAir(InlineResponse20061LastEpisodeToAir lastEpisodeToAir) {
    this.lastEpisodeToAir = lastEpisodeToAir;
    return this;
  }

   /**
   * Get lastEpisodeToAir
   * @return lastEpisodeToAir
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20061LastEpisodeToAir getLastEpisodeToAir() {
    return lastEpisodeToAir;
  }

  public void setLastEpisodeToAir(InlineResponse20061LastEpisodeToAir lastEpisodeToAir) {
    this.lastEpisodeToAir = lastEpisodeToAir;
  }

  public InlineResponse20061 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20061 networks(List<InlineResponse20061Networks> networks) {
    this.networks = networks;
    return this;
  }

  public InlineResponse20061 addNetworksItem(InlineResponse20061Networks networksItem) {
    if (this.networks == null) {
      this.networks = new ArrayList<InlineResponse20061Networks>();
    }
    this.networks.add(networksItem);
    return this;
  }

   /**
   * Get networks
   * @return networks
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20061Networks> getNetworks() {
    return networks;
  }

  public void setNetworks(List<InlineResponse20061Networks> networks) {
    this.networks = networks;
  }

  public InlineResponse20061 numberOfEpisodes(Integer numberOfEpisodes) {
    this.numberOfEpisodes = numberOfEpisodes;
    return this;
  }

   /**
   * Get numberOfEpisodes
   * @return numberOfEpisodes
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfEpisodes() {
    return numberOfEpisodes;
  }

  public void setNumberOfEpisodes(Integer numberOfEpisodes) {
    this.numberOfEpisodes = numberOfEpisodes;
  }

  public InlineResponse20061 numberOfSeasons(Integer numberOfSeasons) {
    this.numberOfSeasons = numberOfSeasons;
    return this;
  }

   /**
   * Get numberOfSeasons
   * @return numberOfSeasons
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfSeasons() {
    return numberOfSeasons;
  }

  public void setNumberOfSeasons(Integer numberOfSeasons) {
    this.numberOfSeasons = numberOfSeasons;
  }

  public InlineResponse20061 originCountry(List<String> originCountry) {
    this.originCountry = originCountry;
    return this;
  }

  public InlineResponse20061 addOriginCountryItem(String originCountryItem) {
    if (this.originCountry == null) {
      this.originCountry = new ArrayList<String>();
    }
    this.originCountry.add(originCountryItem);
    return this;
  }

   /**
   * Get originCountry
   * @return originCountry
  **/
  @ApiModelProperty(value = "")
  public List<String> getOriginCountry() {
    return originCountry;
  }

  public void setOriginCountry(List<String> originCountry) {
    this.originCountry = originCountry;
  }

  public InlineResponse20061 originalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
    return this;
  }

   /**
   * Get originalLanguage
   * @return originalLanguage
  **/
  @ApiModelProperty(value = "")
  public String getOriginalLanguage() {
    return originalLanguage;
  }

  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }

  public InlineResponse20061 originalName(String originalName) {
    this.originalName = originalName;
    return this;
  }

   /**
   * Get originalName
   * @return originalName
  **/
  @ApiModelProperty(value = "")
  public String getOriginalName() {
    return originalName;
  }

  public void setOriginalName(String originalName) {
    this.originalName = originalName;
  }

  public InlineResponse20061 overview(String overview) {
    this.overview = overview;
    return this;
  }

   /**
   * Get overview
   * @return overview
  **/
  @ApiModelProperty(value = "")
  public String getOverview() {
    return overview;
  }

  public void setOverview(String overview) {
    this.overview = overview;
  }

  public InlineResponse20061 popularity(BigDecimal popularity) {
    this.popularity = popularity;
    return this;
  }

   /**
   * Get popularity
   * @return popularity
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPopularity() {
    return popularity;
  }

  public void setPopularity(BigDecimal popularity) {
    this.popularity = popularity;
  }

  public InlineResponse20061 posterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
    return this;
  }

   /**
   * Get posterPath
   * @return posterPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getPosterPath() {
    return posterPath;
  }

  public void setPosterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
  }

  public InlineResponse20061 productionCompanies(List<InlineResponse20061ProductionCompanies> productionCompanies) {
    this.productionCompanies = productionCompanies;
    return this;
  }

  public InlineResponse20061 addProductionCompaniesItem(InlineResponse20061ProductionCompanies productionCompaniesItem) {
    if (this.productionCompanies == null) {
      this.productionCompanies = new ArrayList<InlineResponse20061ProductionCompanies>();
    }
    this.productionCompanies.add(productionCompaniesItem);
    return this;
  }

   /**
   * Get productionCompanies
   * @return productionCompanies
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20061ProductionCompanies> getProductionCompanies() {
    return productionCompanies;
  }

  public void setProductionCompanies(List<InlineResponse20061ProductionCompanies> productionCompanies) {
    this.productionCompanies = productionCompanies;
  }

  public InlineResponse20061 productionCountries(List<InlineResponse20043ProductionCountries> productionCountries) {
    this.productionCountries = productionCountries;
    return this;
  }

  public InlineResponse20061 addProductionCountriesItem(InlineResponse20043ProductionCountries productionCountriesItem) {
    if (this.productionCountries == null) {
      this.productionCountries = new ArrayList<InlineResponse20043ProductionCountries>();
    }
    this.productionCountries.add(productionCountriesItem);
    return this;
  }

   /**
   * Get productionCountries
   * @return productionCountries
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20043ProductionCountries> getProductionCountries() {
    return productionCountries;
  }

  public void setProductionCountries(List<InlineResponse20043ProductionCountries> productionCountries) {
    this.productionCountries = productionCountries;
  }

  public InlineResponse20061 seasons(List<InlineResponse20061Seasons> seasons) {
    this.seasons = seasons;
    return this;
  }

  public InlineResponse20061 addSeasonsItem(InlineResponse20061Seasons seasonsItem) {
    if (this.seasons == null) {
      this.seasons = new ArrayList<InlineResponse20061Seasons>();
    }
    this.seasons.add(seasonsItem);
    return this;
  }

   /**
   * Get seasons
   * @return seasons
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20061Seasons> getSeasons() {
    return seasons;
  }

  public void setSeasons(List<InlineResponse20061Seasons> seasons) {
    this.seasons = seasons;
  }

  public InlineResponse20061 spokenLanguages(List<InlineResponse20061SpokenLanguages> spokenLanguages) {
    this.spokenLanguages = spokenLanguages;
    return this;
  }

  public InlineResponse20061 addSpokenLanguagesItem(InlineResponse20061SpokenLanguages spokenLanguagesItem) {
    if (this.spokenLanguages == null) {
      this.spokenLanguages = new ArrayList<InlineResponse20061SpokenLanguages>();
    }
    this.spokenLanguages.add(spokenLanguagesItem);
    return this;
  }

   /**
   * Get spokenLanguages
   * @return spokenLanguages
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20061SpokenLanguages> getSpokenLanguages() {
    return spokenLanguages;
  }

  public void setSpokenLanguages(List<InlineResponse20061SpokenLanguages> spokenLanguages) {
    this.spokenLanguages = spokenLanguages;
  }

  public InlineResponse20061 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse20061 tagline(String tagline) {
    this.tagline = tagline;
    return this;
  }

   /**
   * Get tagline
   * @return tagline
  **/
  @ApiModelProperty(value = "")
  public String getTagline() {
    return tagline;
  }

  public void setTagline(String tagline) {
    this.tagline = tagline;
  }

  public InlineResponse20061 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public InlineResponse20061 voteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
    return this;
  }

   /**
   * Get voteAverage
   * @return voteAverage
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getVoteAverage() {
    return voteAverage;
  }

  public void setVoteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
  }

  public InlineResponse20061 voteCount(Integer voteCount) {
    this.voteCount = voteCount;
    return this;
  }

   /**
   * Get voteCount
   * @return voteCount
  **/
  @ApiModelProperty(value = "")
  public Integer getVoteCount() {
    return voteCount;
  }

  public void setVoteCount(Integer voteCount) {
    this.voteCount = voteCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20061 inlineResponse20061 = (InlineResponse20061) o;
    return Objects.equals(this.backdropPath, inlineResponse20061.backdropPath) &&
        Objects.equals(this.createdBy, inlineResponse20061.createdBy) &&
        Objects.equals(this.episodeRunTime, inlineResponse20061.episodeRunTime) &&
        Objects.equals(this.firstAirDate, inlineResponse20061.firstAirDate) &&
        Objects.equals(this.genres, inlineResponse20061.genres) &&
        Objects.equals(this.homepage, inlineResponse20061.homepage) &&
        Objects.equals(this.id, inlineResponse20061.id) &&
        Objects.equals(this.inProduction, inlineResponse20061.inProduction) &&
        Objects.equals(this.languages, inlineResponse20061.languages) &&
        Objects.equals(this.lastAirDate, inlineResponse20061.lastAirDate) &&
        Objects.equals(this.lastEpisodeToAir, inlineResponse20061.lastEpisodeToAir) &&
        Objects.equals(this.name, inlineResponse20061.name) &&
        Objects.equals(this.networks, inlineResponse20061.networks) &&
        Objects.equals(this.numberOfEpisodes, inlineResponse20061.numberOfEpisodes) &&
        Objects.equals(this.numberOfSeasons, inlineResponse20061.numberOfSeasons) &&
        Objects.equals(this.originCountry, inlineResponse20061.originCountry) &&
        Objects.equals(this.originalLanguage, inlineResponse20061.originalLanguage) &&
        Objects.equals(this.originalName, inlineResponse20061.originalName) &&
        Objects.equals(this.overview, inlineResponse20061.overview) &&
        Objects.equals(this.popularity, inlineResponse20061.popularity) &&
        Objects.equals(this.posterPath, inlineResponse20061.posterPath) &&
        Objects.equals(this.productionCompanies, inlineResponse20061.productionCompanies) &&
        Objects.equals(this.productionCountries, inlineResponse20061.productionCountries) &&
        Objects.equals(this.seasons, inlineResponse20061.seasons) &&
        Objects.equals(this.spokenLanguages, inlineResponse20061.spokenLanguages) &&
        Objects.equals(this.status, inlineResponse20061.status) &&
        Objects.equals(this.tagline, inlineResponse20061.tagline) &&
        Objects.equals(this.type, inlineResponse20061.type) &&
        Objects.equals(this.voteAverage, inlineResponse20061.voteAverage) &&
        Objects.equals(this.voteCount, inlineResponse20061.voteCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backdropPath, createdBy, episodeRunTime, firstAirDate, genres, homepage, id, inProduction, languages, lastAirDate, lastEpisodeToAir, name, networks, numberOfEpisodes, numberOfSeasons, originCountry, originalLanguage, originalName, overview, popularity, posterPath, productionCompanies, productionCountries, seasons, spokenLanguages, status, tagline, type, voteAverage, voteCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20061 {\n");
    
    sb.append("    backdropPath: ").append(toIndentedString(backdropPath)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    episodeRunTime: ").append(toIndentedString(episodeRunTime)).append("\n");
    sb.append("    firstAirDate: ").append(toIndentedString(firstAirDate)).append("\n");
    sb.append("    genres: ").append(toIndentedString(genres)).append("\n");
    sb.append("    homepage: ").append(toIndentedString(homepage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inProduction: ").append(toIndentedString(inProduction)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    lastAirDate: ").append(toIndentedString(lastAirDate)).append("\n");
    sb.append("    lastEpisodeToAir: ").append(toIndentedString(lastEpisodeToAir)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("    numberOfEpisodes: ").append(toIndentedString(numberOfEpisodes)).append("\n");
    sb.append("    numberOfSeasons: ").append(toIndentedString(numberOfSeasons)).append("\n");
    sb.append("    originCountry: ").append(toIndentedString(originCountry)).append("\n");
    sb.append("    originalLanguage: ").append(toIndentedString(originalLanguage)).append("\n");
    sb.append("    originalName: ").append(toIndentedString(originalName)).append("\n");
    sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
    sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
    sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
    sb.append("    productionCompanies: ").append(toIndentedString(productionCompanies)).append("\n");
    sb.append("    productionCountries: ").append(toIndentedString(productionCountries)).append("\n");
    sb.append("    seasons: ").append(toIndentedString(seasons)).append("\n");
    sb.append("    spokenLanguages: ").append(toIndentedString(spokenLanguages)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tagline: ").append(toIndentedString(tagline)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    voteAverage: ").append(toIndentedString(voteAverage)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

