/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20067Translations;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20067
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20067 {
  @SerializedName("translations")
  private List<InlineResponse20067Translations> translations = null;

  @SerializedName("id")
  private Integer id = null;

  public InlineResponse20067 translations(List<InlineResponse20067Translations> translations) {
    this.translations = translations;
    return this;
  }

  public InlineResponse20067 addTranslationsItem(InlineResponse20067Translations translationsItem) {
    if (this.translations == null) {
      this.translations = new ArrayList<InlineResponse20067Translations>();
    }
    this.translations.add(translationsItem);
    return this;
  }

   /**
   * Get translations
   * @return translations
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20067Translations> getTranslations() {
    return translations;
  }

  public void setTranslations(List<InlineResponse20067Translations> translations) {
    this.translations = translations;
  }

  public InlineResponse20067 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20067 inlineResponse20067 = (InlineResponse20067) o;
    return Objects.equals(this.translations, inlineResponse20067.translations) &&
        Objects.equals(this.id, inlineResponse20067.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(translations, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20067 {\n");
    
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

