/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20041Stills;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20041
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20041 {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("stills")
  private List<InlineResponse20041Stills> stills = null;

  public InlineResponse20041 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20041 stills(List<InlineResponse20041Stills> stills) {
    this.stills = stills;
    return this;
  }

  public InlineResponse20041 addStillsItem(InlineResponse20041Stills stillsItem) {
    if (this.stills == null) {
      this.stills = new ArrayList<InlineResponse20041Stills>();
    }
    this.stills.add(stillsItem);
    return this;
  }

   /**
   * Get stills
   * @return stills
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20041Stills> getStills() {
    return stills;
  }

  public void setStills(List<InlineResponse20041Stills> stills) {
    this.stills = stills;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20041 inlineResponse20041 = (InlineResponse20041) o;
    return Objects.equals(this.id, inlineResponse20041.id) &&
        Objects.equals(this.stills, inlineResponse20041.stills);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, stills);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20041 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    stills: ").append(toIndentedString(stills)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

