/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20049CertificationsUS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20049CertificationsUS {
  @SerializedName("certification")
  private String certification = null;

  @SerializedName("meaning")
  private String meaning = null;

  @SerializedName("order")
  private Integer order = null;

  public InlineResponse20049CertificationsUS certification(String certification) {
    this.certification = certification;
    return this;
  }

   /**
   * Get certification
   * @return certification
  **/
  @ApiModelProperty(value = "")
  public String getCertification() {
    return certification;
  }

  public void setCertification(String certification) {
    this.certification = certification;
  }

  public InlineResponse20049CertificationsUS meaning(String meaning) {
    this.meaning = meaning;
    return this;
  }

   /**
   * Get meaning
   * @return meaning
  **/
  @ApiModelProperty(value = "")
  public String getMeaning() {
    return meaning;
  }

  public void setMeaning(String meaning) {
    this.meaning = meaning;
  }

  public InlineResponse20049CertificationsUS order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(value = "")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20049CertificationsUS inlineResponse20049CertificationsUS = (InlineResponse20049CertificationsUS) o;
    return Objects.equals(this.certification, inlineResponse20049CertificationsUS.certification) &&
        Objects.equals(this.meaning, inlineResponse20049CertificationsUS.meaning) &&
        Objects.equals(this.order, inlineResponse20049CertificationsUS.order);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certification, meaning, order);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20049CertificationsUS {\n");
    
    sb.append("    certification: ").append(toIndentedString(certification)).append("\n");
    sb.append("    meaning: ").append(toIndentedString(meaning)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

