/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ImagePath;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20064Cast
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20064Cast {
  @SerializedName("credit_id")
  private String creditId = null;

  @SerializedName("original_name")
  private String originalName = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("genre_ids")
  private List<Integer> genreIds = null;

  @SerializedName("character")
  private String character = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("poster_path")
  private ImagePath posterPath = null;

  @SerializedName("vote_count")
  private Integer voteCount = null;

  @SerializedName("vote_average")
  private BigDecimal voteAverage = null;

  @SerializedName("popularity")
  private BigDecimal popularity = null;

  @SerializedName("episode_count")
  private Integer episodeCount = null;

  @SerializedName("original_language")
  private String originalLanguage = null;

  @SerializedName("first_air_date")
  private String firstAirDate = null;

  @SerializedName("backdrop_path")
  private ImagePath backdropPath = null;

  @SerializedName("overview")
  private String overview = null;

  @SerializedName("origin_country")
  private List<String> originCountry = null;

  public InlineResponse20064Cast creditId(String creditId) {
    this.creditId = creditId;
    return this;
  }

   /**
   * Get creditId
   * @return creditId
  **/
  @ApiModelProperty(value = "")
  public String getCreditId() {
    return creditId;
  }

  public void setCreditId(String creditId) {
    this.creditId = creditId;
  }

  public InlineResponse20064Cast originalName(String originalName) {
    this.originalName = originalName;
    return this;
  }

   /**
   * Get originalName
   * @return originalName
  **/
  @ApiModelProperty(value = "")
  public String getOriginalName() {
    return originalName;
  }

  public void setOriginalName(String originalName) {
    this.originalName = originalName;
  }

  public InlineResponse20064Cast id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20064Cast genreIds(List<Integer> genreIds) {
    this.genreIds = genreIds;
    return this;
  }

  public InlineResponse20064Cast addGenreIdsItem(Integer genreIdsItem) {
    if (this.genreIds == null) {
      this.genreIds = new ArrayList<Integer>();
    }
    this.genreIds.add(genreIdsItem);
    return this;
  }

   /**
   * Get genreIds
   * @return genreIds
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getGenreIds() {
    return genreIds;
  }

  public void setGenreIds(List<Integer> genreIds) {
    this.genreIds = genreIds;
  }

  public InlineResponse20064Cast character(String character) {
    this.character = character;
    return this;
  }

   /**
   * Get character
   * @return character
  **/
  @ApiModelProperty(value = "")
  public String getCharacter() {
    return character;
  }

  public void setCharacter(String character) {
    this.character = character;
  }

  public InlineResponse20064Cast name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20064Cast posterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
    return this;
  }

   /**
   * Get posterPath
   * @return posterPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getPosterPath() {
    return posterPath;
  }

  public void setPosterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
  }

  public InlineResponse20064Cast voteCount(Integer voteCount) {
    this.voteCount = voteCount;
    return this;
  }

   /**
   * Get voteCount
   * @return voteCount
  **/
  @ApiModelProperty(value = "")
  public Integer getVoteCount() {
    return voteCount;
  }

  public void setVoteCount(Integer voteCount) {
    this.voteCount = voteCount;
  }

  public InlineResponse20064Cast voteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
    return this;
  }

   /**
   * Get voteAverage
   * @return voteAverage
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getVoteAverage() {
    return voteAverage;
  }

  public void setVoteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
  }

  public InlineResponse20064Cast popularity(BigDecimal popularity) {
    this.popularity = popularity;
    return this;
  }

   /**
   * Get popularity
   * @return popularity
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPopularity() {
    return popularity;
  }

  public void setPopularity(BigDecimal popularity) {
    this.popularity = popularity;
  }

  public InlineResponse20064Cast episodeCount(Integer episodeCount) {
    this.episodeCount = episodeCount;
    return this;
  }

   /**
   * Get episodeCount
   * @return episodeCount
  **/
  @ApiModelProperty(value = "")
  public Integer getEpisodeCount() {
    return episodeCount;
  }

  public void setEpisodeCount(Integer episodeCount) {
    this.episodeCount = episodeCount;
  }

  public InlineResponse20064Cast originalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
    return this;
  }

   /**
   * Get originalLanguage
   * @return originalLanguage
  **/
  @ApiModelProperty(value = "")
  public String getOriginalLanguage() {
    return originalLanguage;
  }

  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }

  public InlineResponse20064Cast firstAirDate(String firstAirDate) {
    this.firstAirDate = firstAirDate;
    return this;
  }

   /**
   * Get firstAirDate
   * @return firstAirDate
  **/
  @ApiModelProperty(value = "")
  public String getFirstAirDate() {
    return firstAirDate;
  }

  public void setFirstAirDate(String firstAirDate) {
    this.firstAirDate = firstAirDate;
  }

  public InlineResponse20064Cast backdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
    return this;
  }

   /**
   * Get backdropPath
   * @return backdropPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getBackdropPath() {
    return backdropPath;
  }

  public void setBackdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
  }

  public InlineResponse20064Cast overview(String overview) {
    this.overview = overview;
    return this;
  }

   /**
   * Get overview
   * @return overview
  **/
  @ApiModelProperty(value = "")
  public String getOverview() {
    return overview;
  }

  public void setOverview(String overview) {
    this.overview = overview;
  }

  public InlineResponse20064Cast originCountry(List<String> originCountry) {
    this.originCountry = originCountry;
    return this;
  }

  public InlineResponse20064Cast addOriginCountryItem(String originCountryItem) {
    if (this.originCountry == null) {
      this.originCountry = new ArrayList<String>();
    }
    this.originCountry.add(originCountryItem);
    return this;
  }

   /**
   * Get originCountry
   * @return originCountry
  **/
  @ApiModelProperty(value = "")
  public List<String> getOriginCountry() {
    return originCountry;
  }

  public void setOriginCountry(List<String> originCountry) {
    this.originCountry = originCountry;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20064Cast inlineResponse20064Cast = (InlineResponse20064Cast) o;
    return Objects.equals(this.creditId, inlineResponse20064Cast.creditId) &&
        Objects.equals(this.originalName, inlineResponse20064Cast.originalName) &&
        Objects.equals(this.id, inlineResponse20064Cast.id) &&
        Objects.equals(this.genreIds, inlineResponse20064Cast.genreIds) &&
        Objects.equals(this.character, inlineResponse20064Cast.character) &&
        Objects.equals(this.name, inlineResponse20064Cast.name) &&
        Objects.equals(this.posterPath, inlineResponse20064Cast.posterPath) &&
        Objects.equals(this.voteCount, inlineResponse20064Cast.voteCount) &&
        Objects.equals(this.voteAverage, inlineResponse20064Cast.voteAverage) &&
        Objects.equals(this.popularity, inlineResponse20064Cast.popularity) &&
        Objects.equals(this.episodeCount, inlineResponse20064Cast.episodeCount) &&
        Objects.equals(this.originalLanguage, inlineResponse20064Cast.originalLanguage) &&
        Objects.equals(this.firstAirDate, inlineResponse20064Cast.firstAirDate) &&
        Objects.equals(this.backdropPath, inlineResponse20064Cast.backdropPath) &&
        Objects.equals(this.overview, inlineResponse20064Cast.overview) &&
        Objects.equals(this.originCountry, inlineResponse20064Cast.originCountry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditId, originalName, id, genreIds, character, name, posterPath, voteCount, voteAverage, popularity, episodeCount, originalLanguage, firstAirDate, backdropPath, overview, originCountry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20064Cast {\n");
    
    sb.append("    creditId: ").append(toIndentedString(creditId)).append("\n");
    sb.append("    originalName: ").append(toIndentedString(originalName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    genreIds: ").append(toIndentedString(genreIds)).append("\n");
    sb.append("    character: ").append(toIndentedString(character)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("    voteAverage: ").append(toIndentedString(voteAverage)).append("\n");
    sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
    sb.append("    episodeCount: ").append(toIndentedString(episodeCount)).append("\n");
    sb.append("    originalLanguage: ").append(toIndentedString(originalLanguage)).append("\n");
    sb.append("    firstAirDate: ").append(toIndentedString(firstAirDate)).append("\n");
    sb.append("    backdropPath: ").append(toIndentedString(backdropPath)).append("\n");
    sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
    sb.append("    originCountry: ").append(toIndentedString(originCountry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

