/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2001ResultsAR;
import io.swagger.client.model.InlineResponse2001ResultsAT;
import io.swagger.client.model.InlineResponse2001ResultsJP;
import io.swagger.client.model.InlineResponse20087ResultsAR;
import io.swagger.client.model.InlineResponse20087ResultsAT;
import io.swagger.client.model.InlineResponse20087ResultsAU;
import io.swagger.client.model.InlineResponse20087ResultsBE;
import io.swagger.client.model.InlineResponse20087ResultsCL;
import io.swagger.client.model.InlineResponse20087ResultsKR;
import java.io.IOException;

/**
 * InlineResponse20087Results
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20087Results {
  @SerializedName("AR")
  private InlineResponse20087ResultsAR AR = null;

  @SerializedName("AT")
  private InlineResponse20087ResultsAT AT = null;

  @SerializedName("AU")
  private InlineResponse20087ResultsAU AU = null;

  @SerializedName("BE")
  private InlineResponse20087ResultsBE BE = null;

  @SerializedName("BR")
  private InlineResponse20087ResultsAU BR = null;

  @SerializedName("CA")
  private InlineResponse2001ResultsJP CA = null;

  @SerializedName("CH")
  private InlineResponse20087ResultsAU CH = null;

  @SerializedName("CL")
  private InlineResponse20087ResultsCL CL = null;

  @SerializedName("CO")
  private InlineResponse20087ResultsAR CO = null;

  @SerializedName("CZ")
  private InlineResponse20087ResultsBE CZ = null;

  @SerializedName("DE")
  private InlineResponse20087ResultsAT DE = null;

  @SerializedName("DK")
  private InlineResponse20087ResultsAU DK = null;

  @SerializedName("EC")
  private InlineResponse20087ResultsCL EC = null;

  @SerializedName("EE")
  private InlineResponse20087ResultsCL EE = null;

  @SerializedName("ES")
  private InlineResponse2001ResultsJP ES = null;

  @SerializedName("FI")
  private InlineResponse20087ResultsBE FI = null;

  @SerializedName("FR")
  private InlineResponse20087ResultsCL FR = null;

  @SerializedName("GB")
  private InlineResponse2001ResultsJP GB = null;

  @SerializedName("GR")
  private InlineResponse20087ResultsAR GR = null;

  @SerializedName("HU")
  private InlineResponse20087ResultsAU HU = null;

  @SerializedName("ID")
  private InlineResponse20087ResultsAR ID = null;

  @SerializedName("IE")
  private InlineResponse2001ResultsJP IE = null;

  @SerializedName("IN")
  private InlineResponse20087ResultsBE IN = null;

  @SerializedName("IT")
  private InlineResponse20087ResultsBE IT = null;

  @SerializedName("JP")
  private InlineResponse2001ResultsJP JP = null;

  @SerializedName("KR")
  private InlineResponse20087ResultsKR KR = null;

  @SerializedName("LT")
  private InlineResponse2001ResultsAT LT = null;

  @SerializedName("LV")
  private InlineResponse2001ResultsAT LV = null;

  @SerializedName("MX")
  private InlineResponse20087ResultsAR MX = null;

  @SerializedName("MY")
  private InlineResponse2001ResultsJP MY = null;

  @SerializedName("NL")
  private InlineResponse20087ResultsCL NL = null;

  @SerializedName("NO")
  private InlineResponse20087ResultsKR NO = null;

  @SerializedName("NZ")
  private InlineResponse20087ResultsKR NZ = null;

  @SerializedName("PE")
  private InlineResponse20087ResultsAR PE = null;

  @SerializedName("PH")
  private InlineResponse20087ResultsAU PH = null;

  @SerializedName("PL")
  private InlineResponse2001ResultsJP PL = null;

  @SerializedName("PT")
  private InlineResponse2001ResultsJP PT = null;

  @SerializedName("RO")
  private InlineResponse2001ResultsAR RO = null;

  @SerializedName("RU")
  private InlineResponse2001ResultsJP RU = null;

  @SerializedName("SE")
  private InlineResponse2001ResultsJP SE = null;

  @SerializedName("SG")
  private InlineResponse20087ResultsCL SG = null;

  @SerializedName("TH")
  private InlineResponse20087ResultsAR TH = null;

  @SerializedName("TR")
  private InlineResponse20087ResultsKR TR = null;

  @SerializedName("US")
  private InlineResponse20087ResultsAU US = null;

  @SerializedName("VE")
  private InlineResponse20087ResultsAR VE = null;

  @SerializedName("ZA")
  private InlineResponse20087ResultsAU ZA = null;

  public InlineResponse20087Results AR(InlineResponse20087ResultsAR AR) {
    this.AR = AR;
    return this;
  }

   /**
   * Get AR
   * @return AR
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAR getAR() {
    return AR;
  }

  public void setAR(InlineResponse20087ResultsAR AR) {
    this.AR = AR;
  }

  public InlineResponse20087Results AT(InlineResponse20087ResultsAT AT) {
    this.AT = AT;
    return this;
  }

   /**
   * Get AT
   * @return AT
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAT getAT() {
    return AT;
  }

  public void setAT(InlineResponse20087ResultsAT AT) {
    this.AT = AT;
  }

  public InlineResponse20087Results AU(InlineResponse20087ResultsAU AU) {
    this.AU = AU;
    return this;
  }

   /**
   * Get AU
   * @return AU
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAU getAU() {
    return AU;
  }

  public void setAU(InlineResponse20087ResultsAU AU) {
    this.AU = AU;
  }

  public InlineResponse20087Results BE(InlineResponse20087ResultsBE BE) {
    this.BE = BE;
    return this;
  }

   /**
   * Get BE
   * @return BE
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsBE getBE() {
    return BE;
  }

  public void setBE(InlineResponse20087ResultsBE BE) {
    this.BE = BE;
  }

  public InlineResponse20087Results BR(InlineResponse20087ResultsAU BR) {
    this.BR = BR;
    return this;
  }

   /**
   * Get BR
   * @return BR
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAU getBR() {
    return BR;
  }

  public void setBR(InlineResponse20087ResultsAU BR) {
    this.BR = BR;
  }

  public InlineResponse20087Results CA(InlineResponse2001ResultsJP CA) {
    this.CA = CA;
    return this;
  }

   /**
   * Get CA
   * @return CA
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getCA() {
    return CA;
  }

  public void setCA(InlineResponse2001ResultsJP CA) {
    this.CA = CA;
  }

  public InlineResponse20087Results CH(InlineResponse20087ResultsAU CH) {
    this.CH = CH;
    return this;
  }

   /**
   * Get CH
   * @return CH
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAU getCH() {
    return CH;
  }

  public void setCH(InlineResponse20087ResultsAU CH) {
    this.CH = CH;
  }

  public InlineResponse20087Results CL(InlineResponse20087ResultsCL CL) {
    this.CL = CL;
    return this;
  }

   /**
   * Get CL
   * @return CL
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsCL getCL() {
    return CL;
  }

  public void setCL(InlineResponse20087ResultsCL CL) {
    this.CL = CL;
  }

  public InlineResponse20087Results CO(InlineResponse20087ResultsAR CO) {
    this.CO = CO;
    return this;
  }

   /**
   * Get CO
   * @return CO
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAR getCO() {
    return CO;
  }

  public void setCO(InlineResponse20087ResultsAR CO) {
    this.CO = CO;
  }

  public InlineResponse20087Results CZ(InlineResponse20087ResultsBE CZ) {
    this.CZ = CZ;
    return this;
  }

   /**
   * Get CZ
   * @return CZ
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsBE getCZ() {
    return CZ;
  }

  public void setCZ(InlineResponse20087ResultsBE CZ) {
    this.CZ = CZ;
  }

  public InlineResponse20087Results DE(InlineResponse20087ResultsAT DE) {
    this.DE = DE;
    return this;
  }

   /**
   * Get DE
   * @return DE
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAT getDE() {
    return DE;
  }

  public void setDE(InlineResponse20087ResultsAT DE) {
    this.DE = DE;
  }

  public InlineResponse20087Results DK(InlineResponse20087ResultsAU DK) {
    this.DK = DK;
    return this;
  }

   /**
   * Get DK
   * @return DK
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAU getDK() {
    return DK;
  }

  public void setDK(InlineResponse20087ResultsAU DK) {
    this.DK = DK;
  }

  public InlineResponse20087Results EC(InlineResponse20087ResultsCL EC) {
    this.EC = EC;
    return this;
  }

   /**
   * Get EC
   * @return EC
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsCL getEC() {
    return EC;
  }

  public void setEC(InlineResponse20087ResultsCL EC) {
    this.EC = EC;
  }

  public InlineResponse20087Results EE(InlineResponse20087ResultsCL EE) {
    this.EE = EE;
    return this;
  }

   /**
   * Get EE
   * @return EE
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsCL getEE() {
    return EE;
  }

  public void setEE(InlineResponse20087ResultsCL EE) {
    this.EE = EE;
  }

  public InlineResponse20087Results ES(InlineResponse2001ResultsJP ES) {
    this.ES = ES;
    return this;
  }

   /**
   * Get ES
   * @return ES
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getES() {
    return ES;
  }

  public void setES(InlineResponse2001ResultsJP ES) {
    this.ES = ES;
  }

  public InlineResponse20087Results FI(InlineResponse20087ResultsBE FI) {
    this.FI = FI;
    return this;
  }

   /**
   * Get FI
   * @return FI
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsBE getFI() {
    return FI;
  }

  public void setFI(InlineResponse20087ResultsBE FI) {
    this.FI = FI;
  }

  public InlineResponse20087Results FR(InlineResponse20087ResultsCL FR) {
    this.FR = FR;
    return this;
  }

   /**
   * Get FR
   * @return FR
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsCL getFR() {
    return FR;
  }

  public void setFR(InlineResponse20087ResultsCL FR) {
    this.FR = FR;
  }

  public InlineResponse20087Results GB(InlineResponse2001ResultsJP GB) {
    this.GB = GB;
    return this;
  }

   /**
   * Get GB
   * @return GB
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getGB() {
    return GB;
  }

  public void setGB(InlineResponse2001ResultsJP GB) {
    this.GB = GB;
  }

  public InlineResponse20087Results GR(InlineResponse20087ResultsAR GR) {
    this.GR = GR;
    return this;
  }

   /**
   * Get GR
   * @return GR
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAR getGR() {
    return GR;
  }

  public void setGR(InlineResponse20087ResultsAR GR) {
    this.GR = GR;
  }

  public InlineResponse20087Results HU(InlineResponse20087ResultsAU HU) {
    this.HU = HU;
    return this;
  }

   /**
   * Get HU
   * @return HU
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAU getHU() {
    return HU;
  }

  public void setHU(InlineResponse20087ResultsAU HU) {
    this.HU = HU;
  }

  public InlineResponse20087Results ID(InlineResponse20087ResultsAR ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAR getID() {
    return ID;
  }

  public void setID(InlineResponse20087ResultsAR ID) {
    this.ID = ID;
  }

  public InlineResponse20087Results IE(InlineResponse2001ResultsJP IE) {
    this.IE = IE;
    return this;
  }

   /**
   * Get IE
   * @return IE
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getIE() {
    return IE;
  }

  public void setIE(InlineResponse2001ResultsJP IE) {
    this.IE = IE;
  }

  public InlineResponse20087Results IN(InlineResponse20087ResultsBE IN) {
    this.IN = IN;
    return this;
  }

   /**
   * Get IN
   * @return IN
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsBE getIN() {
    return IN;
  }

  public void setIN(InlineResponse20087ResultsBE IN) {
    this.IN = IN;
  }

  public InlineResponse20087Results IT(InlineResponse20087ResultsBE IT) {
    this.IT = IT;
    return this;
  }

   /**
   * Get IT
   * @return IT
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsBE getIT() {
    return IT;
  }

  public void setIT(InlineResponse20087ResultsBE IT) {
    this.IT = IT;
  }

  public InlineResponse20087Results JP(InlineResponse2001ResultsJP JP) {
    this.JP = JP;
    return this;
  }

   /**
   * Get JP
   * @return JP
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getJP() {
    return JP;
  }

  public void setJP(InlineResponse2001ResultsJP JP) {
    this.JP = JP;
  }

  public InlineResponse20087Results KR(InlineResponse20087ResultsKR KR) {
    this.KR = KR;
    return this;
  }

   /**
   * Get KR
   * @return KR
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsKR getKR() {
    return KR;
  }

  public void setKR(InlineResponse20087ResultsKR KR) {
    this.KR = KR;
  }

  public InlineResponse20087Results LT(InlineResponse2001ResultsAT LT) {
    this.LT = LT;
    return this;
  }

   /**
   * Get LT
   * @return LT
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsAT getLT() {
    return LT;
  }

  public void setLT(InlineResponse2001ResultsAT LT) {
    this.LT = LT;
  }

  public InlineResponse20087Results LV(InlineResponse2001ResultsAT LV) {
    this.LV = LV;
    return this;
  }

   /**
   * Get LV
   * @return LV
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsAT getLV() {
    return LV;
  }

  public void setLV(InlineResponse2001ResultsAT LV) {
    this.LV = LV;
  }

  public InlineResponse20087Results MX(InlineResponse20087ResultsAR MX) {
    this.MX = MX;
    return this;
  }

   /**
   * Get MX
   * @return MX
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAR getMX() {
    return MX;
  }

  public void setMX(InlineResponse20087ResultsAR MX) {
    this.MX = MX;
  }

  public InlineResponse20087Results MY(InlineResponse2001ResultsJP MY) {
    this.MY = MY;
    return this;
  }

   /**
   * Get MY
   * @return MY
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getMY() {
    return MY;
  }

  public void setMY(InlineResponse2001ResultsJP MY) {
    this.MY = MY;
  }

  public InlineResponse20087Results NL(InlineResponse20087ResultsCL NL) {
    this.NL = NL;
    return this;
  }

   /**
   * Get NL
   * @return NL
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsCL getNL() {
    return NL;
  }

  public void setNL(InlineResponse20087ResultsCL NL) {
    this.NL = NL;
  }

  public InlineResponse20087Results NO(InlineResponse20087ResultsKR NO) {
    this.NO = NO;
    return this;
  }

   /**
   * Get NO
   * @return NO
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsKR getNO() {
    return NO;
  }

  public void setNO(InlineResponse20087ResultsKR NO) {
    this.NO = NO;
  }

  public InlineResponse20087Results NZ(InlineResponse20087ResultsKR NZ) {
    this.NZ = NZ;
    return this;
  }

   /**
   * Get NZ
   * @return NZ
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsKR getNZ() {
    return NZ;
  }

  public void setNZ(InlineResponse20087ResultsKR NZ) {
    this.NZ = NZ;
  }

  public InlineResponse20087Results PE(InlineResponse20087ResultsAR PE) {
    this.PE = PE;
    return this;
  }

   /**
   * Get PE
   * @return PE
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAR getPE() {
    return PE;
  }

  public void setPE(InlineResponse20087ResultsAR PE) {
    this.PE = PE;
  }

  public InlineResponse20087Results PH(InlineResponse20087ResultsAU PH) {
    this.PH = PH;
    return this;
  }

   /**
   * Get PH
   * @return PH
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAU getPH() {
    return PH;
  }

  public void setPH(InlineResponse20087ResultsAU PH) {
    this.PH = PH;
  }

  public InlineResponse20087Results PL(InlineResponse2001ResultsJP PL) {
    this.PL = PL;
    return this;
  }

   /**
   * Get PL
   * @return PL
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getPL() {
    return PL;
  }

  public void setPL(InlineResponse2001ResultsJP PL) {
    this.PL = PL;
  }

  public InlineResponse20087Results PT(InlineResponse2001ResultsJP PT) {
    this.PT = PT;
    return this;
  }

   /**
   * Get PT
   * @return PT
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getPT() {
    return PT;
  }

  public void setPT(InlineResponse2001ResultsJP PT) {
    this.PT = PT;
  }

  public InlineResponse20087Results RO(InlineResponse2001ResultsAR RO) {
    this.RO = RO;
    return this;
  }

   /**
   * Get RO
   * @return RO
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsAR getRO() {
    return RO;
  }

  public void setRO(InlineResponse2001ResultsAR RO) {
    this.RO = RO;
  }

  public InlineResponse20087Results RU(InlineResponse2001ResultsJP RU) {
    this.RU = RU;
    return this;
  }

   /**
   * Get RU
   * @return RU
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getRU() {
    return RU;
  }

  public void setRU(InlineResponse2001ResultsJP RU) {
    this.RU = RU;
  }

  public InlineResponse20087Results SE(InlineResponse2001ResultsJP SE) {
    this.SE = SE;
    return this;
  }

   /**
   * Get SE
   * @return SE
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001ResultsJP getSE() {
    return SE;
  }

  public void setSE(InlineResponse2001ResultsJP SE) {
    this.SE = SE;
  }

  public InlineResponse20087Results SG(InlineResponse20087ResultsCL SG) {
    this.SG = SG;
    return this;
  }

   /**
   * Get SG
   * @return SG
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsCL getSG() {
    return SG;
  }

  public void setSG(InlineResponse20087ResultsCL SG) {
    this.SG = SG;
  }

  public InlineResponse20087Results TH(InlineResponse20087ResultsAR TH) {
    this.TH = TH;
    return this;
  }

   /**
   * Get TH
   * @return TH
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAR getTH() {
    return TH;
  }

  public void setTH(InlineResponse20087ResultsAR TH) {
    this.TH = TH;
  }

  public InlineResponse20087Results TR(InlineResponse20087ResultsKR TR) {
    this.TR = TR;
    return this;
  }

   /**
   * Get TR
   * @return TR
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsKR getTR() {
    return TR;
  }

  public void setTR(InlineResponse20087ResultsKR TR) {
    this.TR = TR;
  }

  public InlineResponse20087Results US(InlineResponse20087ResultsAU US) {
    this.US = US;
    return this;
  }

   /**
   * Get US
   * @return US
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAU getUS() {
    return US;
  }

  public void setUS(InlineResponse20087ResultsAU US) {
    this.US = US;
  }

  public InlineResponse20087Results VE(InlineResponse20087ResultsAR VE) {
    this.VE = VE;
    return this;
  }

   /**
   * Get VE
   * @return VE
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAR getVE() {
    return VE;
  }

  public void setVE(InlineResponse20087ResultsAR VE) {
    this.VE = VE;
  }

  public InlineResponse20087Results ZA(InlineResponse20087ResultsAU ZA) {
    this.ZA = ZA;
    return this;
  }

   /**
   * Get ZA
   * @return ZA
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20087ResultsAU getZA() {
    return ZA;
  }

  public void setZA(InlineResponse20087ResultsAU ZA) {
    this.ZA = ZA;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20087Results inlineResponse20087Results = (InlineResponse20087Results) o;
    return Objects.equals(this.AR, inlineResponse20087Results.AR) &&
        Objects.equals(this.AT, inlineResponse20087Results.AT) &&
        Objects.equals(this.AU, inlineResponse20087Results.AU) &&
        Objects.equals(this.BE, inlineResponse20087Results.BE) &&
        Objects.equals(this.BR, inlineResponse20087Results.BR) &&
        Objects.equals(this.CA, inlineResponse20087Results.CA) &&
        Objects.equals(this.CH, inlineResponse20087Results.CH) &&
        Objects.equals(this.CL, inlineResponse20087Results.CL) &&
        Objects.equals(this.CO, inlineResponse20087Results.CO) &&
        Objects.equals(this.CZ, inlineResponse20087Results.CZ) &&
        Objects.equals(this.DE, inlineResponse20087Results.DE) &&
        Objects.equals(this.DK, inlineResponse20087Results.DK) &&
        Objects.equals(this.EC, inlineResponse20087Results.EC) &&
        Objects.equals(this.EE, inlineResponse20087Results.EE) &&
        Objects.equals(this.ES, inlineResponse20087Results.ES) &&
        Objects.equals(this.FI, inlineResponse20087Results.FI) &&
        Objects.equals(this.FR, inlineResponse20087Results.FR) &&
        Objects.equals(this.GB, inlineResponse20087Results.GB) &&
        Objects.equals(this.GR, inlineResponse20087Results.GR) &&
        Objects.equals(this.HU, inlineResponse20087Results.HU) &&
        Objects.equals(this.ID, inlineResponse20087Results.ID) &&
        Objects.equals(this.IE, inlineResponse20087Results.IE) &&
        Objects.equals(this.IN, inlineResponse20087Results.IN) &&
        Objects.equals(this.IT, inlineResponse20087Results.IT) &&
        Objects.equals(this.JP, inlineResponse20087Results.JP) &&
        Objects.equals(this.KR, inlineResponse20087Results.KR) &&
        Objects.equals(this.LT, inlineResponse20087Results.LT) &&
        Objects.equals(this.LV, inlineResponse20087Results.LV) &&
        Objects.equals(this.MX, inlineResponse20087Results.MX) &&
        Objects.equals(this.MY, inlineResponse20087Results.MY) &&
        Objects.equals(this.NL, inlineResponse20087Results.NL) &&
        Objects.equals(this.NO, inlineResponse20087Results.NO) &&
        Objects.equals(this.NZ, inlineResponse20087Results.NZ) &&
        Objects.equals(this.PE, inlineResponse20087Results.PE) &&
        Objects.equals(this.PH, inlineResponse20087Results.PH) &&
        Objects.equals(this.PL, inlineResponse20087Results.PL) &&
        Objects.equals(this.PT, inlineResponse20087Results.PT) &&
        Objects.equals(this.RO, inlineResponse20087Results.RO) &&
        Objects.equals(this.RU, inlineResponse20087Results.RU) &&
        Objects.equals(this.SE, inlineResponse20087Results.SE) &&
        Objects.equals(this.SG, inlineResponse20087Results.SG) &&
        Objects.equals(this.TH, inlineResponse20087Results.TH) &&
        Objects.equals(this.TR, inlineResponse20087Results.TR) &&
        Objects.equals(this.US, inlineResponse20087Results.US) &&
        Objects.equals(this.VE, inlineResponse20087Results.VE) &&
        Objects.equals(this.ZA, inlineResponse20087Results.ZA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(AR, AT, AU, BE, BR, CA, CH, CL, CO, CZ, DE, DK, EC, EE, ES, FI, FR, GB, GR, HU, ID, IE, IN, IT, JP, KR, LT, LV, MX, MY, NL, NO, NZ, PE, PH, PL, PT, RO, RU, SE, SG, TH, TR, US, VE, ZA);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20087Results {\n");
    
    sb.append("    AR: ").append(toIndentedString(AR)).append("\n");
    sb.append("    AT: ").append(toIndentedString(AT)).append("\n");
    sb.append("    AU: ").append(toIndentedString(AU)).append("\n");
    sb.append("    BE: ").append(toIndentedString(BE)).append("\n");
    sb.append("    BR: ").append(toIndentedString(BR)).append("\n");
    sb.append("    CA: ").append(toIndentedString(CA)).append("\n");
    sb.append("    CH: ").append(toIndentedString(CH)).append("\n");
    sb.append("    CL: ").append(toIndentedString(CL)).append("\n");
    sb.append("    CO: ").append(toIndentedString(CO)).append("\n");
    sb.append("    CZ: ").append(toIndentedString(CZ)).append("\n");
    sb.append("    DE: ").append(toIndentedString(DE)).append("\n");
    sb.append("    DK: ").append(toIndentedString(DK)).append("\n");
    sb.append("    EC: ").append(toIndentedString(EC)).append("\n");
    sb.append("    EE: ").append(toIndentedString(EE)).append("\n");
    sb.append("    ES: ").append(toIndentedString(ES)).append("\n");
    sb.append("    FI: ").append(toIndentedString(FI)).append("\n");
    sb.append("    FR: ").append(toIndentedString(FR)).append("\n");
    sb.append("    GB: ").append(toIndentedString(GB)).append("\n");
    sb.append("    GR: ").append(toIndentedString(GR)).append("\n");
    sb.append("    HU: ").append(toIndentedString(HU)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    IE: ").append(toIndentedString(IE)).append("\n");
    sb.append("    IN: ").append(toIndentedString(IN)).append("\n");
    sb.append("    IT: ").append(toIndentedString(IT)).append("\n");
    sb.append("    JP: ").append(toIndentedString(JP)).append("\n");
    sb.append("    KR: ").append(toIndentedString(KR)).append("\n");
    sb.append("    LT: ").append(toIndentedString(LT)).append("\n");
    sb.append("    LV: ").append(toIndentedString(LV)).append("\n");
    sb.append("    MX: ").append(toIndentedString(MX)).append("\n");
    sb.append("    MY: ").append(toIndentedString(MY)).append("\n");
    sb.append("    NL: ").append(toIndentedString(NL)).append("\n");
    sb.append("    NO: ").append(toIndentedString(NO)).append("\n");
    sb.append("    NZ: ").append(toIndentedString(NZ)).append("\n");
    sb.append("    PE: ").append(toIndentedString(PE)).append("\n");
    sb.append("    PH: ").append(toIndentedString(PH)).append("\n");
    sb.append("    PL: ").append(toIndentedString(PL)).append("\n");
    sb.append("    PT: ").append(toIndentedString(PT)).append("\n");
    sb.append("    RO: ").append(toIndentedString(RO)).append("\n");
    sb.append("    RU: ").append(toIndentedString(RU)).append("\n");
    sb.append("    SE: ").append(toIndentedString(SE)).append("\n");
    sb.append("    SG: ").append(toIndentedString(SG)).append("\n");
    sb.append("    TH: ").append(toIndentedString(TH)).append("\n");
    sb.append("    TR: ").append(toIndentedString(TR)).append("\n");
    sb.append("    US: ").append(toIndentedString(US)).append("\n");
    sb.append("    VE: ").append(toIndentedString(VE)).append("\n");
    sb.append("    ZA: ").append(toIndentedString(ZA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

