/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20044MediaSeasons;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20044Media
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20044Media {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("original_name")
  private String originalName = null;

  @SerializedName("character")
  private String character = null;

  @SerializedName("episodes")
  private List<Object> episodes = null;

  @SerializedName("seasons")
  private List<InlineResponse20044MediaSeasons> seasons = null;

  public InlineResponse20044Media id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20044Media name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20044Media originalName(String originalName) {
    this.originalName = originalName;
    return this;
  }

   /**
   * Get originalName
   * @return originalName
  **/
  @ApiModelProperty(value = "")
  public String getOriginalName() {
    return originalName;
  }

  public void setOriginalName(String originalName) {
    this.originalName = originalName;
  }

  public InlineResponse20044Media character(String character) {
    this.character = character;
    return this;
  }

   /**
   * Get character
   * @return character
  **/
  @ApiModelProperty(value = "")
  public String getCharacter() {
    return character;
  }

  public void setCharacter(String character) {
    this.character = character;
  }

  public InlineResponse20044Media episodes(List<Object> episodes) {
    this.episodes = episodes;
    return this;
  }

  public InlineResponse20044Media addEpisodesItem(Object episodesItem) {
    if (this.episodes == null) {
      this.episodes = new ArrayList<Object>();
    }
    this.episodes.add(episodesItem);
    return this;
  }

   /**
   * Get episodes
   * @return episodes
  **/
  @ApiModelProperty(value = "")
  public List<Object> getEpisodes() {
    return episodes;
  }

  public void setEpisodes(List<Object> episodes) {
    this.episodes = episodes;
  }

  public InlineResponse20044Media seasons(List<InlineResponse20044MediaSeasons> seasons) {
    this.seasons = seasons;
    return this;
  }

  public InlineResponse20044Media addSeasonsItem(InlineResponse20044MediaSeasons seasonsItem) {
    if (this.seasons == null) {
      this.seasons = new ArrayList<InlineResponse20044MediaSeasons>();
    }
    this.seasons.add(seasonsItem);
    return this;
  }

   /**
   * Get seasons
   * @return seasons
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20044MediaSeasons> getSeasons() {
    return seasons;
  }

  public void setSeasons(List<InlineResponse20044MediaSeasons> seasons) {
    this.seasons = seasons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20044Media inlineResponse20044Media = (InlineResponse20044Media) o;
    return Objects.equals(this.id, inlineResponse20044Media.id) &&
        Objects.equals(this.name, inlineResponse20044Media.name) &&
        Objects.equals(this.originalName, inlineResponse20044Media.originalName) &&
        Objects.equals(this.character, inlineResponse20044Media.character) &&
        Objects.equals(this.episodes, inlineResponse20044Media.episodes) &&
        Objects.equals(this.seasons, inlineResponse20044Media.seasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, originalName, character, episodes, seasons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20044Media {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    originalName: ").append(toIndentedString(originalName)).append("\n");
    sb.append("    character: ").append(toIndentedString(character)).append("\n");
    sb.append("    episodes: ").append(toIndentedString(episodes)).append("\n");
    sb.append("    seasons: ").append(toIndentedString(seasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

