/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MovieListObject;
import io.swagger.client.model.PersonListResultsObject;
import io.swagger.client.model.TvListResultObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20032
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20032 {
  @SerializedName("movie_results")
  private List<MovieListObject> movieResults = null;

  @SerializedName("person_results")
  private List<PersonListResultsObject> personResults = null;

  @SerializedName("tv_results")
  private List<TvListResultObject> tvResults = null;

  @SerializedName("tv_episode_results")
  private List<Object> tvEpisodeResults = null;

  @SerializedName("tv_season_results")
  private List<Object> tvSeasonResults = null;

  public InlineResponse20032 movieResults(List<MovieListObject> movieResults) {
    this.movieResults = movieResults;
    return this;
  }

  public InlineResponse20032 addMovieResultsItem(MovieListObject movieResultsItem) {
    if (this.movieResults == null) {
      this.movieResults = new ArrayList<MovieListObject>();
    }
    this.movieResults.add(movieResultsItem);
    return this;
  }

   /**
   * Get movieResults
   * @return movieResults
  **/
  @ApiModelProperty(value = "")
  public List<MovieListObject> getMovieResults() {
    return movieResults;
  }

  public void setMovieResults(List<MovieListObject> movieResults) {
    this.movieResults = movieResults;
  }

  public InlineResponse20032 personResults(List<PersonListResultsObject> personResults) {
    this.personResults = personResults;
    return this;
  }

  public InlineResponse20032 addPersonResultsItem(PersonListResultsObject personResultsItem) {
    if (this.personResults == null) {
      this.personResults = new ArrayList<PersonListResultsObject>();
    }
    this.personResults.add(personResultsItem);
    return this;
  }

   /**
   * Get personResults
   * @return personResults
  **/
  @ApiModelProperty(value = "")
  public List<PersonListResultsObject> getPersonResults() {
    return personResults;
  }

  public void setPersonResults(List<PersonListResultsObject> personResults) {
    this.personResults = personResults;
  }

  public InlineResponse20032 tvResults(List<TvListResultObject> tvResults) {
    this.tvResults = tvResults;
    return this;
  }

  public InlineResponse20032 addTvResultsItem(TvListResultObject tvResultsItem) {
    if (this.tvResults == null) {
      this.tvResults = new ArrayList<TvListResultObject>();
    }
    this.tvResults.add(tvResultsItem);
    return this;
  }

   /**
   * Get tvResults
   * @return tvResults
  **/
  @ApiModelProperty(value = "")
  public List<TvListResultObject> getTvResults() {
    return tvResults;
  }

  public void setTvResults(List<TvListResultObject> tvResults) {
    this.tvResults = tvResults;
  }

  public InlineResponse20032 tvEpisodeResults(List<Object> tvEpisodeResults) {
    this.tvEpisodeResults = tvEpisodeResults;
    return this;
  }

  public InlineResponse20032 addTvEpisodeResultsItem(Object tvEpisodeResultsItem) {
    if (this.tvEpisodeResults == null) {
      this.tvEpisodeResults = new ArrayList<Object>();
    }
    this.tvEpisodeResults.add(tvEpisodeResultsItem);
    return this;
  }

   /**
   * Get tvEpisodeResults
   * @return tvEpisodeResults
  **/
  @ApiModelProperty(value = "")
  public List<Object> getTvEpisodeResults() {
    return tvEpisodeResults;
  }

  public void setTvEpisodeResults(List<Object> tvEpisodeResults) {
    this.tvEpisodeResults = tvEpisodeResults;
  }

  public InlineResponse20032 tvSeasonResults(List<Object> tvSeasonResults) {
    this.tvSeasonResults = tvSeasonResults;
    return this;
  }

  public InlineResponse20032 addTvSeasonResultsItem(Object tvSeasonResultsItem) {
    if (this.tvSeasonResults == null) {
      this.tvSeasonResults = new ArrayList<Object>();
    }
    this.tvSeasonResults.add(tvSeasonResultsItem);
    return this;
  }

   /**
   * Get tvSeasonResults
   * @return tvSeasonResults
  **/
  @ApiModelProperty(value = "")
  public List<Object> getTvSeasonResults() {
    return tvSeasonResults;
  }

  public void setTvSeasonResults(List<Object> tvSeasonResults) {
    this.tvSeasonResults = tvSeasonResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20032 inlineResponse20032 = (InlineResponse20032) o;
    return Objects.equals(this.movieResults, inlineResponse20032.movieResults) &&
        Objects.equals(this.personResults, inlineResponse20032.personResults) &&
        Objects.equals(this.tvResults, inlineResponse20032.tvResults) &&
        Objects.equals(this.tvEpisodeResults, inlineResponse20032.tvEpisodeResults) &&
        Objects.equals(this.tvSeasonResults, inlineResponse20032.tvSeasonResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(movieResults, personResults, tvResults, tvEpisodeResults, tvSeasonResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20032 {\n");
    
    sb.append("    movieResults: ").append(toIndentedString(movieResults)).append("\n");
    sb.append("    personResults: ").append(toIndentedString(personResults)).append("\n");
    sb.append("    tvResults: ").append(toIndentedString(tvResults)).append("\n");
    sb.append("    tvEpisodeResults: ").append(toIndentedString(tvEpisodeResults)).append("\n");
    sb.append("    tvSeasonResults: ").append(toIndentedString(tvSeasonResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

