/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ImagePath;
import io.swagger.client.model.InlineResponse2009Results;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20077
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class InlineResponse20077 {
  @SerializedName("adult")
  private Boolean adult = null;

  @SerializedName("backdrop_path")
  private ImagePath backdropPath = null;

  @SerializedName("budget")
  private Integer budget = null;

  @SerializedName("genres")
  private List<InlineResponse2009Results> genres = null;

  @SerializedName("homepage")
  private String homepage = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("imdb_id")
  private String imdbId = null;

  @SerializedName("original_language")
  private String originalLanguage = null;

  @SerializedName("original_title")
  private String originalTitle = null;

  @SerializedName("overview")
  private String overview = null;

  @SerializedName("popularity")
  private Integer popularity = null;

  @SerializedName("poster_path")
  private ImagePath posterPath = null;

  @SerializedName("production_companies")
  private List<Object> productionCompanies = null;

  @SerializedName("production_countries")
  private List<Object> productionCountries = null;

  @SerializedName("release_date")
  private String releaseDate = null;

  @SerializedName("revenue")
  private Integer revenue = null;

  @SerializedName("runtime")
  private Integer runtime = null;

  @SerializedName("spoken_languages")
  private List<Object> spokenLanguages = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("tagline")
  private String tagline = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("video")
  private Boolean video = null;

  @SerializedName("vote_average")
  private Integer voteAverage = null;

  @SerializedName("vote_count")
  private Integer voteCount = null;

  public InlineResponse20077 adult(Boolean adult) {
    this.adult = adult;
    return this;
  }

   /**
   * Get adult
   * @return adult
  **/
  @ApiModelProperty(value = "")
  public Boolean isAdult() {
    return adult;
  }

  public void setAdult(Boolean adult) {
    this.adult = adult;
  }

  public InlineResponse20077 backdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
    return this;
  }

   /**
   * Get backdropPath
   * @return backdropPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getBackdropPath() {
    return backdropPath;
  }

  public void setBackdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
  }

  public InlineResponse20077 budget(Integer budget) {
    this.budget = budget;
    return this;
  }

   /**
   * Get budget
   * @return budget
  **/
  @ApiModelProperty(value = "")
  public Integer getBudget() {
    return budget;
  }

  public void setBudget(Integer budget) {
    this.budget = budget;
  }

  public InlineResponse20077 genres(List<InlineResponse2009Results> genres) {
    this.genres = genres;
    return this;
  }

  public InlineResponse20077 addGenresItem(InlineResponse2009Results genresItem) {
    if (this.genres == null) {
      this.genres = new ArrayList<InlineResponse2009Results>();
    }
    this.genres.add(genresItem);
    return this;
  }

   /**
   * Get genres
   * @return genres
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2009Results> getGenres() {
    return genres;
  }

  public void setGenres(List<InlineResponse2009Results> genres) {
    this.genres = genres;
  }

  public InlineResponse20077 homepage(String homepage) {
    this.homepage = homepage;
    return this;
  }

   /**
   * Get homepage
   * @return homepage
  **/
  @ApiModelProperty(value = "")
  public String getHomepage() {
    return homepage;
  }

  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public InlineResponse20077 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20077 imdbId(String imdbId) {
    this.imdbId = imdbId;
    return this;
  }

   /**
   * Get imdbId
   * @return imdbId
  **/
  @ApiModelProperty(value = "")
  public String getImdbId() {
    return imdbId;
  }

  public void setImdbId(String imdbId) {
    this.imdbId = imdbId;
  }

  public InlineResponse20077 originalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
    return this;
  }

   /**
   * Get originalLanguage
   * @return originalLanguage
  **/
  @ApiModelProperty(value = "")
  public String getOriginalLanguage() {
    return originalLanguage;
  }

  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }

  public InlineResponse20077 originalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
    return this;
  }

   /**
   * Get originalTitle
   * @return originalTitle
  **/
  @ApiModelProperty(value = "")
  public String getOriginalTitle() {
    return originalTitle;
  }

  public void setOriginalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
  }

  public InlineResponse20077 overview(String overview) {
    this.overview = overview;
    return this;
  }

   /**
   * Get overview
   * @return overview
  **/
  @ApiModelProperty(value = "")
  public String getOverview() {
    return overview;
  }

  public void setOverview(String overview) {
    this.overview = overview;
  }

  public InlineResponse20077 popularity(Integer popularity) {
    this.popularity = popularity;
    return this;
  }

   /**
   * Get popularity
   * @return popularity
  **/
  @ApiModelProperty(value = "")
  public Integer getPopularity() {
    return popularity;
  }

  public void setPopularity(Integer popularity) {
    this.popularity = popularity;
  }

  public InlineResponse20077 posterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
    return this;
  }

   /**
   * Get posterPath
   * @return posterPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getPosterPath() {
    return posterPath;
  }

  public void setPosterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
  }

  public InlineResponse20077 productionCompanies(List<Object> productionCompanies) {
    this.productionCompanies = productionCompanies;
    return this;
  }

  public InlineResponse20077 addProductionCompaniesItem(Object productionCompaniesItem) {
    if (this.productionCompanies == null) {
      this.productionCompanies = new ArrayList<Object>();
    }
    this.productionCompanies.add(productionCompaniesItem);
    return this;
  }

   /**
   * Get productionCompanies
   * @return productionCompanies
  **/
  @ApiModelProperty(value = "")
  public List<Object> getProductionCompanies() {
    return productionCompanies;
  }

  public void setProductionCompanies(List<Object> productionCompanies) {
    this.productionCompanies = productionCompanies;
  }

  public InlineResponse20077 productionCountries(List<Object> productionCountries) {
    this.productionCountries = productionCountries;
    return this;
  }

  public InlineResponse20077 addProductionCountriesItem(Object productionCountriesItem) {
    if (this.productionCountries == null) {
      this.productionCountries = new ArrayList<Object>();
    }
    this.productionCountries.add(productionCountriesItem);
    return this;
  }

   /**
   * Get productionCountries
   * @return productionCountries
  **/
  @ApiModelProperty(value = "")
  public List<Object> getProductionCountries() {
    return productionCountries;
  }

  public void setProductionCountries(List<Object> productionCountries) {
    this.productionCountries = productionCountries;
  }

  public InlineResponse20077 releaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @ApiModelProperty(value = "")
  public String getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
  }

  public InlineResponse20077 revenue(Integer revenue) {
    this.revenue = revenue;
    return this;
  }

   /**
   * Get revenue
   * @return revenue
  **/
  @ApiModelProperty(value = "")
  public Integer getRevenue() {
    return revenue;
  }

  public void setRevenue(Integer revenue) {
    this.revenue = revenue;
  }

  public InlineResponse20077 runtime(Integer runtime) {
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @ApiModelProperty(value = "")
  public Integer getRuntime() {
    return runtime;
  }

  public void setRuntime(Integer runtime) {
    this.runtime = runtime;
  }

  public InlineResponse20077 spokenLanguages(List<Object> spokenLanguages) {
    this.spokenLanguages = spokenLanguages;
    return this;
  }

  public InlineResponse20077 addSpokenLanguagesItem(Object spokenLanguagesItem) {
    if (this.spokenLanguages == null) {
      this.spokenLanguages = new ArrayList<Object>();
    }
    this.spokenLanguages.add(spokenLanguagesItem);
    return this;
  }

   /**
   * Get spokenLanguages
   * @return spokenLanguages
  **/
  @ApiModelProperty(value = "")
  public List<Object> getSpokenLanguages() {
    return spokenLanguages;
  }

  public void setSpokenLanguages(List<Object> spokenLanguages) {
    this.spokenLanguages = spokenLanguages;
  }

  public InlineResponse20077 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse20077 tagline(String tagline) {
    this.tagline = tagline;
    return this;
  }

   /**
   * Get tagline
   * @return tagline
  **/
  @ApiModelProperty(value = "")
  public String getTagline() {
    return tagline;
  }

  public void setTagline(String tagline) {
    this.tagline = tagline;
  }

  public InlineResponse20077 title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public InlineResponse20077 video(Boolean video) {
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @ApiModelProperty(value = "")
  public Boolean isVideo() {
    return video;
  }

  public void setVideo(Boolean video) {
    this.video = video;
  }

  public InlineResponse20077 voteAverage(Integer voteAverage) {
    this.voteAverage = voteAverage;
    return this;
  }

   /**
   * Get voteAverage
   * @return voteAverage
  **/
  @ApiModelProperty(value = "")
  public Integer getVoteAverage() {
    return voteAverage;
  }

  public void setVoteAverage(Integer voteAverage) {
    this.voteAverage = voteAverage;
  }

  public InlineResponse20077 voteCount(Integer voteCount) {
    this.voteCount = voteCount;
    return this;
  }

   /**
   * Get voteCount
   * @return voteCount
  **/
  @ApiModelProperty(value = "")
  public Integer getVoteCount() {
    return voteCount;
  }

  public void setVoteCount(Integer voteCount) {
    this.voteCount = voteCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20077 inlineResponse20077 = (InlineResponse20077) o;
    return Objects.equals(this.adult, inlineResponse20077.adult) &&
        Objects.equals(this.backdropPath, inlineResponse20077.backdropPath) &&
        Objects.equals(this.budget, inlineResponse20077.budget) &&
        Objects.equals(this.genres, inlineResponse20077.genres) &&
        Objects.equals(this.homepage, inlineResponse20077.homepage) &&
        Objects.equals(this.id, inlineResponse20077.id) &&
        Objects.equals(this.imdbId, inlineResponse20077.imdbId) &&
        Objects.equals(this.originalLanguage, inlineResponse20077.originalLanguage) &&
        Objects.equals(this.originalTitle, inlineResponse20077.originalTitle) &&
        Objects.equals(this.overview, inlineResponse20077.overview) &&
        Objects.equals(this.popularity, inlineResponse20077.popularity) &&
        Objects.equals(this.posterPath, inlineResponse20077.posterPath) &&
        Objects.equals(this.productionCompanies, inlineResponse20077.productionCompanies) &&
        Objects.equals(this.productionCountries, inlineResponse20077.productionCountries) &&
        Objects.equals(this.releaseDate, inlineResponse20077.releaseDate) &&
        Objects.equals(this.revenue, inlineResponse20077.revenue) &&
        Objects.equals(this.runtime, inlineResponse20077.runtime) &&
        Objects.equals(this.spokenLanguages, inlineResponse20077.spokenLanguages) &&
        Objects.equals(this.status, inlineResponse20077.status) &&
        Objects.equals(this.tagline, inlineResponse20077.tagline) &&
        Objects.equals(this.title, inlineResponse20077.title) &&
        Objects.equals(this.video, inlineResponse20077.video) &&
        Objects.equals(this.voteAverage, inlineResponse20077.voteAverage) &&
        Objects.equals(this.voteCount, inlineResponse20077.voteCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adult, backdropPath, budget, genres, homepage, id, imdbId, originalLanguage, originalTitle, overview, popularity, posterPath, productionCompanies, productionCountries, releaseDate, revenue, runtime, spokenLanguages, status, tagline, title, video, voteAverage, voteCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20077 {\n");
    
    sb.append("    adult: ").append(toIndentedString(adult)).append("\n");
    sb.append("    backdropPath: ").append(toIndentedString(backdropPath)).append("\n");
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    genres: ").append(toIndentedString(genres)).append("\n");
    sb.append("    homepage: ").append(toIndentedString(homepage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imdbId: ").append(toIndentedString(imdbId)).append("\n");
    sb.append("    originalLanguage: ").append(toIndentedString(originalLanguage)).append("\n");
    sb.append("    originalTitle: ").append(toIndentedString(originalTitle)).append("\n");
    sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
    sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
    sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
    sb.append("    productionCompanies: ").append(toIndentedString(productionCompanies)).append("\n");
    sb.append("    productionCountries: ").append(toIndentedString(productionCountries)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    spokenLanguages: ").append(toIndentedString(spokenLanguages)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tagline: ").append(toIndentedString(tagline)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    voteAverage: ").append(toIndentedString(voteAverage)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

