/*
 * API
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ImagePath;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * MovieListResultsObjectWithMediaType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-13T09:38:01.485+02:00")
public class MovieListResultsObjectWithMediaType {
  @SerializedName("poster_path")
  private ImagePath posterPath = null;

  @SerializedName("adult")
  private Boolean adult = null;

  @SerializedName("overview")
  private String overview = null;

  @SerializedName("release_date")
  private String releaseDate = null;

  @SerializedName("original_title")
  private String originalTitle = null;

  @SerializedName("genre_ids")
  private List<Integer> genreIds = null;

  @SerializedName("id")
  private Integer id = null;

  /**
   * Gets or Sets mediaType
   */
  @JsonAdapter(MediaTypeEnum.Adapter.class)
  public enum MediaTypeEnum {
    MOVIE("movie");

    private String value;

    MediaTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MediaTypeEnum fromValue(String text) {
      for (MediaTypeEnum b : MediaTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<MediaTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MediaTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MediaTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return MediaTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("media_type")
  private MediaTypeEnum mediaType = null;

  @SerializedName("original_language")
  private String originalLanguage = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("backdrop_path")
  private ImagePath backdropPath = null;

  @SerializedName("popularity")
  private BigDecimal popularity = null;

  @SerializedName("vote_count")
  private Integer voteCount = null;

  @SerializedName("video")
  private Boolean video = null;

  @SerializedName("vote_average")
  private BigDecimal voteAverage = null;

  public MovieListResultsObjectWithMediaType posterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
    return this;
  }

   /**
   * Get posterPath
   * @return posterPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getPosterPath() {
    return posterPath;
  }

  public void setPosterPath(ImagePath posterPath) {
    this.posterPath = posterPath;
  }

  public MovieListResultsObjectWithMediaType adult(Boolean adult) {
    this.adult = adult;
    return this;
  }

   /**
   * Get adult
   * @return adult
  **/
  @ApiModelProperty(value = "")
  public Boolean isAdult() {
    return adult;
  }

  public void setAdult(Boolean adult) {
    this.adult = adult;
  }

  public MovieListResultsObjectWithMediaType overview(String overview) {
    this.overview = overview;
    return this;
  }

   /**
   * Get overview
   * @return overview
  **/
  @ApiModelProperty(value = "")
  public String getOverview() {
    return overview;
  }

  public void setOverview(String overview) {
    this.overview = overview;
  }

  public MovieListResultsObjectWithMediaType releaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @ApiModelProperty(value = "")
  public String getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
  }

  public MovieListResultsObjectWithMediaType originalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
    return this;
  }

   /**
   * Get originalTitle
   * @return originalTitle
  **/
  @ApiModelProperty(value = "")
  public String getOriginalTitle() {
    return originalTitle;
  }

  public void setOriginalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
  }

  public MovieListResultsObjectWithMediaType genreIds(List<Integer> genreIds) {
    this.genreIds = genreIds;
    return this;
  }

  public MovieListResultsObjectWithMediaType addGenreIdsItem(Integer genreIdsItem) {
    if (this.genreIds == null) {
      this.genreIds = new ArrayList<Integer>();
    }
    this.genreIds.add(genreIdsItem);
    return this;
  }

   /**
   * Get genreIds
   * @return genreIds
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getGenreIds() {
    return genreIds;
  }

  public void setGenreIds(List<Integer> genreIds) {
    this.genreIds = genreIds;
  }

  public MovieListResultsObjectWithMediaType id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MovieListResultsObjectWithMediaType mediaType(MediaTypeEnum mediaType) {
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Get mediaType
   * @return mediaType
  **/
  @ApiModelProperty(required = true, value = "")
  public MediaTypeEnum getMediaType() {
    return mediaType;
  }

  public void setMediaType(MediaTypeEnum mediaType) {
    this.mediaType = mediaType;
  }

  public MovieListResultsObjectWithMediaType originalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
    return this;
  }

   /**
   * Get originalLanguage
   * @return originalLanguage
  **/
  @ApiModelProperty(value = "")
  public String getOriginalLanguage() {
    return originalLanguage;
  }

  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }

  public MovieListResultsObjectWithMediaType title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public MovieListResultsObjectWithMediaType backdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
    return this;
  }

   /**
   * Get backdropPath
   * @return backdropPath
  **/
  @ApiModelProperty(value = "")
  public ImagePath getBackdropPath() {
    return backdropPath;
  }

  public void setBackdropPath(ImagePath backdropPath) {
    this.backdropPath = backdropPath;
  }

  public MovieListResultsObjectWithMediaType popularity(BigDecimal popularity) {
    this.popularity = popularity;
    return this;
  }

   /**
   * Get popularity
   * @return popularity
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPopularity() {
    return popularity;
  }

  public void setPopularity(BigDecimal popularity) {
    this.popularity = popularity;
  }

  public MovieListResultsObjectWithMediaType voteCount(Integer voteCount) {
    this.voteCount = voteCount;
    return this;
  }

   /**
   * Get voteCount
   * @return voteCount
  **/
  @ApiModelProperty(value = "")
  public Integer getVoteCount() {
    return voteCount;
  }

  public void setVoteCount(Integer voteCount) {
    this.voteCount = voteCount;
  }

  public MovieListResultsObjectWithMediaType video(Boolean video) {
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @ApiModelProperty(value = "")
  public Boolean isVideo() {
    return video;
  }

  public void setVideo(Boolean video) {
    this.video = video;
  }

  public MovieListResultsObjectWithMediaType voteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
    return this;
  }

   /**
   * Get voteAverage
   * @return voteAverage
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getVoteAverage() {
    return voteAverage;
  }

  public void setVoteAverage(BigDecimal voteAverage) {
    this.voteAverage = voteAverage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieListResultsObjectWithMediaType movieListResultsObjectWithMediaType = (MovieListResultsObjectWithMediaType) o;
    return Objects.equals(this.posterPath, movieListResultsObjectWithMediaType.posterPath) &&
        Objects.equals(this.adult, movieListResultsObjectWithMediaType.adult) &&
        Objects.equals(this.overview, movieListResultsObjectWithMediaType.overview) &&
        Objects.equals(this.releaseDate, movieListResultsObjectWithMediaType.releaseDate) &&
        Objects.equals(this.originalTitle, movieListResultsObjectWithMediaType.originalTitle) &&
        Objects.equals(this.genreIds, movieListResultsObjectWithMediaType.genreIds) &&
        Objects.equals(this.id, movieListResultsObjectWithMediaType.id) &&
        Objects.equals(this.mediaType, movieListResultsObjectWithMediaType.mediaType) &&
        Objects.equals(this.originalLanguage, movieListResultsObjectWithMediaType.originalLanguage) &&
        Objects.equals(this.title, movieListResultsObjectWithMediaType.title) &&
        Objects.equals(this.backdropPath, movieListResultsObjectWithMediaType.backdropPath) &&
        Objects.equals(this.popularity, movieListResultsObjectWithMediaType.popularity) &&
        Objects.equals(this.voteCount, movieListResultsObjectWithMediaType.voteCount) &&
        Objects.equals(this.video, movieListResultsObjectWithMediaType.video) &&
        Objects.equals(this.voteAverage, movieListResultsObjectWithMediaType.voteAverage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posterPath, adult, overview, releaseDate, originalTitle, genreIds, id, mediaType, originalLanguage, title, backdropPath, popularity, voteCount, video, voteAverage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieListResultsObjectWithMediaType {\n");
    
    sb.append("    posterPath: ").append(toIndentedString(posterPath)).append("\n");
    sb.append("    adult: ").append(toIndentedString(adult)).append("\n");
    sb.append("    overview: ").append(toIndentedString(overview)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    originalTitle: ").append(toIndentedString(originalTitle)).append("\n");
    sb.append("    genreIds: ").append(toIndentedString(genreIds)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    originalLanguage: ").append(toIndentedString(originalLanguage)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    backdropPath: ").append(toIndentedString(backdropPath)).append("\n");
    sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    voteAverage: ").append(toIndentedString(voteAverage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

